services:
  db:
    image: postgres:18-alpine
    container_name: mando_voc_db
    env_file:
      - conf/database/.env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
      - 5432:5432
    restart: no
    volumes:
      - pg_data:/var/lib/postgresql
      - ./conf/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    image: mando_voc_server
    container_name: mando_voc_server
    build:
      dockerfile: conf/docker/Dockerfile.dev
      target: server
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - conf/database/.env.dev
      - packages/server/.env.dev
    healthcheck:
      test: curl --fail http://localhost:5174/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    ports:
      - 5174:5174
    restart: no
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/server/node_modules

  client:
    image: mando_voc_client
    container_name: mando_voc_client
    build:
      dockerfile: conf/docker/Dockerfile.dev
      target: client
    depends_on:
      server:
        condition: service_healthy
    ports:
      - 5173:5173
    restart: no
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/client/node_modules

volumes:
  pg_data: {}