services:
  db:
    image: postgres:18-alpine
    container_name: mando_voc_db
    restart: no
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql
      - ./conf/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - conf/database/.env.dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    image: mando_voc_server
    container_name: mando_voc_server
    build:
      context: .
      dockerfile: conf/docker/Dockerfile.dev
      target: server
    env_file:
      - ./packages/server/.env.dev
    restart: no
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 5174:5174
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/server/node_modules

  client:
    image: mando_voc_client
    container_name: mando_voc_client
    build:
      context: .
      dockerfile: conf/docker/Dockerfile.dev
      target: client
    restart: no
    depends_on:
      - server
    ports:
      - 5173:5173
    volumes:
      - .:/app
      - /app/node_modules
      - /app/packages/client/node_modules

volumes:
  pg_data: {}