FROM node:24-slim AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME/bin:$PATH"
ENV CI=true
RUN corepack enable

WORKDIR /app

COPY --parents --exclude=node_modules **/package.json pnpm-*.yaml ./
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install -r --frozen-lockfile


FROM base AS server

WORKDIR /app/packages/server

RUN apt update && apt install -y --no-install-recommends curl

CMD ["pnpm", "run", "dev"]


FROM base AS client

WORKDIR /app/packages/client

CMD ["pnpm", "run", "dev"]